#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Temporal Analysis Engine Implementation

set -e

echo "========================================"
echo "Temporal Analysis Engine - Dev Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# DEPENDENCY INSTALLATION
# ============================================

echo ""
echo "Installing dependencies..."
echo ""

# Check if chrono-node is installed
if ! grep -q "chrono-node" package.json 2>/dev/null; then
    echo -e "${YELLOW}chrono-node not found in package.json - needs manual addition${NC}"
    echo "Please add: \"chrono-node\": \"^2.7.0\" to dependencies"
fi

# Install Node dependencies (if package.json was modified)
if [ -f package.json ]; then
    echo "Running npm install..."
    npm install
fi

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo ""
echo "Starting Next.js development server..."
echo ""

# Start Next.js in background
npm run dev &
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js Dev: http://localhost:3000"
echo ""
echo "Next Steps:"
echo "  1. Verify chrono-node is in package.json dependencies"
echo "  2. Run: npm install (if you added chrono-node)"
echo "  3. Begin implementation of temporal analysis engine"
echo "  4. Run tests: npm test -- src/__tests__/engines/temporal.test.ts"
echo ""
echo "Key Files:"
echo "  - src/lib/engines/temporal.ts (main implementation)"
echo "  - src/__tests__/engines/temporal.test.ts (tests)"
echo "  - package.json (add chrono-node dependency)"
echo ""
